apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mlflow.port }}
        env:
        - name: MLFLOW_BACKEND_STORE_URI
          value: "{{ .Values.mlflow.backendStoreUri }}"
        - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
          value: "{{ .Values.mlflow.defaultArtifactRoot }}"
        volumeMounts:
        - name: mlflow-data
          mountPath: /app
      volumes:
      - name: mlflow-data
        persistentVolumeClaim:
          claimName: mlflow-pvc
