apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-fastapi"
  labels:
    app: fastapi
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: fastapi
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.images.fastapi.repository }}:{{ .Values.images.fastapi.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy | default 'IfNotPresent' }}"
          ports:
            - containerPort: {{ .Values.services.fastapi.port }}
          readinessProbe:
            httpGet:
              path: "/health"
              port: {{ .Values.services.fastapi.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: "/health"
              port: {{ .Values.services.fastapi.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
