apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-fastapi"
  labels:
    app: fastapi
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: fastapi
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.fastapi.port }}
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-fastapi-configmap"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.fastapi.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.fastapi.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
