apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-fastapi"
  labels:
    app: fastapi
    release: "{{ .Release.Name }}"
spec:
  type: "{{ .Values.services.fastapi.type }}"
  ports:
    - port: {{ .Values.services.fastapi.port }}
      targetPort: {{ .Values.services.fastapi.port }}
      protocol: TCP
  selector:
    app: fastapi
    release: "{{ .Release.Name }}"
