version: '3.9'

services:
  mlops-app:
    build:
      context: .  # Build the Dockerfile in the current directory
    ports:
      - "5000:5000"  # Expose the app on localhost:5000
    volumes:
    - .:/app  # Mount the project directory to /app in the container
    - ./data:/data  # Mount the data directory if needed
    depends_on:
      - mlflow
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # Connect to MLflow
    command: ["python", "./app/mlflow_train.py"]
