apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-jenkins-pvc"
  labels:
    app: jenkins
spec:
  accessModes:
    - "{{ .Values.persistence.accessMode }}"
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
  storageClassName: "{{ .Values.persistence.storageClass | default 'standard' }}"
