import numpy as np
import json

# Define the desired order for the ordinal columns, including np.nan to handle missing values
RESPONSE_TIME_ORDER = ['within an hour', 'within a few hours', 'within a day', 'a few days or more', np.nan]
CANCELLATION_POLICY_ORDER = ['flexible', 'moderate', 'strict', 'strict_14_with_grace_period', 'super_strict_30', 'super_strict_60', np.nan]
TEST_INPUT = {
    "Unnamed: 0": 10,
    "id": 48901,
    "listing_url": "https://www.airbnb.com/rooms/48901",
    "scrape_id": 20180816030859,
    "last_scraped": "2018-08-16",
    "name": "Special deal 4 BR beach corner",
    "summary": "Very confortable and safe this 4/4 unit is well decorated confortable  counts on amazing location - a few steps only from Copacabana beach, easy transportation and shopping, 4 air conditioned bedrooms, wifi/cable, parking , for an amazing low price.",
    "space": "Excellent 4 bedroom apartment, located on Copacabana beach (with a side view to the ocean), confortable, afordable, priviledged location. Easy transportation on the neighbourhood, lots of shops and restaurants, beach access + very easy tansportation anywhere in Rio 15 away minutes from Santos Dumont airport and  20 \u00b4 from bus station",
    "description": "Very confortable and safe this 4/4 unit is well decorated confortable  counts on amazing location - a few steps only from Copacabana beach, easy transportation and shopping, 4 air conditioned bedrooms, wifi/cable, parking , for an amazing low price. Excellent 4 bedroom apartment, located on Copacabana beach (with a side view to the ocean), confortable, afordable, priviledged location. Easy transportation on the neighbourhood, lots of shops and restaurants, beach access + very easy tansportation anywhere in Rio 15 away minutes from Santos Dumont airport and  20 \u00b4 from bus station Excelent supermarket, varied stores and restaurants, Copacabana beach afew steps away Easy to find a taxi or a bus, walking is ALWAYS an option to most places in Rio. A few blocks away from RioMetro. Electricity by kilowatts Apartment is great for 8 guests ( two more possible at an extra charge)",
    "experiences_offered": "none",
    "neighborhood_overview": "Excelent supermarket, varied stores and restaurants, Copacabana beach afew steps away",
    "notes": "Electricity by kilowatts Apartment is great for 8 guests ( two more possible at an extra charge)",
    "transit": "Easy to find a taxi or a bus, walking is ALWAYS an option to most places in Rio. A few blocks away from RioMetro.",
    "access": "A praia de Copacabana est\u00e1 distante a poucos passos de nosso edif\u00edcio. Durante o Reveillon a cobertura do edif\u00edcio permaner\u00e1 aberta durante a queima de fogos.para um numero limitado de h\u00f3spedes",
    "interaction": None,
    "house_rules": "Wi- Fi / cable Included Gas/water included SECURITY DEPOSIT REQUIRED  US$ 500,00 AT ARRIVAL Clean bed sheets/bath towels included.",
    "thumbnail_url": None,
    "medium_url": None,
    "picture_url": "https://a0.muscache.com/im/pictures/30577488/cba6f57c_original.jpg?aki_policy=large",
    "xl_picture_url": None,
    "host_id": 222884,
    "host_url": "https://www.airbnb.com/users/show/222884",
    "host_name": "Marcio",
    "host_since": "2010-09-03",
    "host_location": "Rio de Janeiro, Rio de Janeiro, Brazil",
    "host_about": "Viajante do mundo com experienci\u00eas nos 5 continentes...",
    "host_response_time": "within an hour",
    "host_response_rate": "100%",
    "host_acceptance_rate": None,
    "host_is_superhost": "f",
    "host_thumbnail_url": "https://a0.muscache.com/im/users/222884/profile_pic/1283553621/original.jpg?aki_policy=profile_small",
    "host_picture_url": "https://a0.muscache.com/im/users/222884/profile_pic/1283553621/original.jpg?aki_policy=profile_x_medium",
    "host_neighbourhood": "Copacabana",
    "host_listings_count": 7.0,
    "host_total_listings_count": 7.0,
    "host_verifications": "['email', 'phone', 'facebook', 'reviews', 'jumio', 'offline_government_id', 'government_id']",
    "host_has_profile_pic": "t",
    "host_identity_verified": "t",
    "street": "Rio, Rio de Janeiro, Brazil",
    "neighbourhood": "Copacabana",
    "neighbourhood_cleansed": "Copacabana",
    "neighbourhood_group_cleansed": None,
    "city": "Rio",
    "state": "Rio de Janeiro",
    "zipcode": "22021",
    "market": "Rio De Janeiro",
    "smart_location": "Rio, Brazil",
    "country_code": "BR",
    "country": "Brazil",
    "latitude": -22.964674754,
    "longitude": -43.1744184569,
    "is_location_exact": "t",
    "property_type": "Apartment",
    "room_type": "Entire home/apt",
    "accommodates": 11,
    "bathrooms": 3.5,
    "bedrooms": 4.0,
}
