# FastAPI configurations
fastapi:
  replicaCount: 1                     # Number of FastAPI replicas
  port: 8000                          # Port FastAPI listens on
  pipelineArtifactPath: pipeline/preprocessing_pipeline.pkl  # Path to pipeline artifact
  experimentName: hyperparameter_tuning  # MLflow experiment name
  modelName: decision_tree            # Model name
  modelVersion: latest                # Model version

# MLflow configurations (reuse existing)
mlflow:
  backendStoreUri: sqlite:///mlflow.db  # Path for backend storage
  defaultArtifactRoot: /mlruns          # Path for artifact storage
  port: 5000                            # Port MLflow server listens on

# Docker image details for FastAPI
image:
  repository: fastapi                  # Docker image repository for FastAPI
  tag: latest                          # Docker image tag
  pullPolicy: Never                    # Image pull policy
