apiVersion: v1
kind: Service
metadata:
  name: mlflow_train
spec:
  type: {{ .Values.services.mlflow_train.type }}
  ports:
  - port: {{ .Values.services.mlflow_train.port }}
    targetPort: 5000
  selector:
    app: mlflow_train
