name: mlflow-node
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - scikit-learn
  - protobuf<=3.20.3
  - sqlalchemy<2.0
  - mlflow
  - pip
  - pip:
      - uvicorn
      - fastapi
      - pydantic
