apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-mlflow-pvc"
  labels:
    app: mlflow
spec:
  accessModes:
    - '{{ .Values.persistence.accessMode | default "ReadWriteOnce" }}'
  resources:
    requests:
      storage: '{{ .Values.persistence.size | default "1Gi" }}'
  storageClassName: '{{ .Values.persistence.storageClass | default "standard" }}'
