dependencies:
- name: mlflow
  alias: mlflow
  version: 1.0.0
  repository: file://./mlflow
  condition: mlflow.enabled # Dynamically enabled or disabled in values.yaml
- name: fastapi
  alias: fastapi
  version: 1.0.0
  repository: file://./fastapi
# No condition, disabled by default in values.yaml
- name: jenkins
  alias: jenkins
  version: 1.0.0
  repository: file://./jenkins
# No condition, disabled by default in values.yaml
- name: airflow
  alias: airflow
  version: 1.0.0
  repository: file://./airflow
# No condition, disabled by default in values.yaml
