apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.images.fastapi.repository }}:{{ .Values.images.fastapi.tag }}"
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
          ports:
            - containerPort: 8000
          command: ["uvicorn", "app.fastapi:app", "--host", "0.0.0.0", "--port", "8000"]
